drop table if exists accounts;

create sequence test_seq;

create table accounts (
  --id integer primary key,
  id integer generated by default as sequence test_seq,
  name varchar(30),
  surname varchar(30),
  PRIMARY KEY (ID)
);